Repository WildCodeSchool/orleans-0219-php-planet-mini-basket, pull requests merged in 2019-04, with the labels that each got.

#3 Sprint01 us03 banniere accueil
  composer.lock
  public/assets/css/style.css
  src/Controller/ItemController.php
  src/View/Home/_banner.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#7 Intégration de la bannière sur master
  composer.lock
  public/assets/css/style.css
  src/Controller/ItemController.php
  src/View/Home/_banner.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#5 creating section in Home index block content
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed by PO

#10 Merge dev to Master
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#6 Les trois cards info de la page d'accueil
  public/assets/css/style.css
  src/View/Home/_info.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#4 Sprint1 us1 /navbar
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.svg
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2
  public/assets/fonts/icomoon/icomoon.eot
  public/assets/fonts/icomoon/icomoon.svg
  public/assets/fonts/icomoon/icomoon.ttf
  public/assets/fonts/icomoon/icomoon.woff
  public/assets/images/Logo5.png
  public/assets/js/index.js
  src/View/Home/index.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#9 Us 14 page accueil meilleures activités
  public/assets/css/style.css
  public/assets/images/bestActivitieDance.jpg
  public/assets/images/bestActivitiesBasket.jpg
  public/assets/images/bestActivitiesEquitation.jpg
  public/assets/images/placeholder-Copy-3-1.png
  src/View/Home/index.html.twig
  src/View/_bestActivities.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#13 Changed borders info color to orange
  public/assets/css/style.css
  src/View/Home/_info.html.twig
Labels: Reviewed by PO

#12 Changement d'image et section info en dessous du jumbotron
  public/assets/css/style.css
  public/assets/images/bannerProjet4.jpg
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#11 News section to dev
  public/assets/css/style.css
  public/assets/js/index.js
  src/Controller/HomeController.php
  src/Model/NewsManager.php
  src/View/Home/_carousel.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#15 Sprint02 us10 tarifs
  public/assets/css/style.css
  src/Controller/PriceController.php
  src/Model/PriceManager.php
  src/View/Price/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#8 Sprint1 us2 footer
  public/assets/css/style.css
  public/assets/images/logoFooter.png
  src/View/Home/index.html.twig
  src/View/_footer.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#18 Sprint2 us39 mentions legales
  public/assets/css/style.css
  src/Controller/LegalMentionsController.php
  src/View/LegalMentions/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#17 Sprint02 us30 nos stages
  public/assets/css/stage.css
  public/assets/images/stages/baseball.jpg
  public/assets/images/stages/christmas.jpg
  public/assets/images/stages/hockey.jpg
  public/assets/images/stages/kidball.jpg
  public/assets/images/stages/paque.jpg
  public/assets/images/stages/zombie.jpg
  src/Controller/StageController.php
  src/Model/StageManager.php
  src/View/Stage/index.html.twig
Labels: Corrections done, Reviewed by PO

#19 fix layout
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#20 Correction bug fix
  public/assets/css/stage.css
  public/assets/css/style.css
  src/Controller/LegalMentionsController.php
  src/Controller/PriceController.php
  src/View/Home/_banner.html.twig
  src/View/Home/_bestActivities.html.twig
  src/View/Home/_carousel.html.twig
  src/View/Home/_info.html.twig
  src/View/_bestActivities.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#14 Merge FAQ to DEV
  composer.json
  composer.lock
  public/assets/css/style.css
  src/Controller/FaqController.php
  src/Model/FaqManager.php
  src/View/Faq/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#24 Again Correction on dev
  public/assets/css/style.css
  src/View/Home/_bestActivities.html.twig
  src/View/Home/index.html.twig
  src/View/Price/index.html.twig
Labels: Reviewed by PO

#26 Pull request Dev to Master
  composer.json
  composer.lock
  public/assets/css/navbar.css
  public/assets/css/stage.css
  public/assets/css/style.css
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.svg
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
  public/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2
  public/assets/fonts/icomoon/icomoon.eot
  public/assets/fonts/icomoon/icomoon.svg
  public/assets/fonts/icomoon/icomoon.ttf
  public/assets/fonts/icomoon/icomoon.woff
  public/assets/images/Logo5.png
  public/assets/images/bannerProjet4.jpg
  public/assets/images/bestActivitieDance.jpg
  public/assets/images/bestActivitiesBasket.jpg
  public/assets/images/bestActivitiesEquitation.jpg
  public/assets/images/logoFooter.png
  public/assets/images/placeholder-Copy-3-1.png
  public/assets/images/stages/baseball.jpg
  public/assets/images/stages/christmas.jpg
  public/assets/images/stages/hockey.jpg
  public/assets/images/stages/kidball.jpg
  public/assets/images/stages/paque.jpg
  public/assets/images/stages/zombie.jpg
  public/assets/js/index.js
  src/Controller/FaqController.php
  src/Controller/HomeController.php
  src/Controller/LegalMentionsController.php
  src/Controller/PriceController.php
  src/Controller/StageController.php
  src/Model/FaqManager.php
  src/Model/NewsManager.php
  src/Model/PriceManager.php
  src/Model/StageManager.php
  src/View/Faq/index.html.twig
  src/View/Home/_banner.html.twig
  src/View/Home/_bestActivities.html.twig
  src/View/Home/_carousel.html.twig
  src/View/Home/_info.html.twig
  src/View/Home/index.html.twig
  src/View/LegalMentions/index.html.twig
  src/View/Price/index.html.twig
  src/View/Stage/index.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#23 gestion actualités ajouter admin vers dev
  src/Controller/NewsAdminController.php
  src/Model/NewsManager.php
  src/View/NewsAdmin/_form.html.twig
  src/View/NewsAdmin/add.html.twig
  src/View/NewsAdmin/show.html.twig
  src/tools/CleanData.php
Labels: Corrections done, Reviewed by PO

#30 change color font awesom and text in stage page
  public/assets/css/stage.css
  src/View/Stage/index.html.twig
Labels: Reviewed by PO

#28 Sprint03 us15 presentation infrastructures
  public/assets/css/style.css
  public/assets/images/gymnaseBarthelemy.jpeg
  public/assets/images/gymnasePlanete.jpg
  public/assets/images/placeholder-Copy-3-1.png
  src/Controller/PresentationController.php
  src/Model/PlaceManager.php
  src/View/Presentation/index.html.twig
Labels: Corrections done, Reviewed by PO

#32 Sprint4 us54 vue admin nostages
  src/Controller/StageAdminController.php
  src/View/StageAdmin/index.html.twig
Labels: Reviewed by PO

#33 US_56 client requests ok
  public/assets/css/style.css
  src/View/Price/index.html.twig
Labels: Reviewed by PO

#34 Sprint02 us30 nos stages fix date time mercredi
  src/View/Stage/index.html.twig
Labels: Reviewed by PO

#35 U61 layout admin
  src/View/layoutAdmin.html.twig
Labels: Reviewed by PO

#31 Sprint4 us51 connexion bdd afficher index news back office #27
  src/Controller/NewsAdminController.php
  src/View/NewsAdmin/index.html.twig
Labels: Reviewed by PO

#36 Sprint04 us60 presentation equipe
  public/assets/images/quiSommesNous.jpg
  src/Controller/PresentationController.php
  src/Model/PresentationManager.php
  src/View/Presentation/index.html.twig
Labels: Reviewed by PO

#39 Sprint3 us24 news gestion/add
  src/View/NewsAdmin/_form.html.twig
  src/View/NewsAdmin/add.html.twig
Labels: Reviewed by PO

#41 Sprint04 us65 navbar admin
  public/assets/css/admin.css
  src/View/_navbarAdmin.htm.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed by PO

#37 Sprint04 us62 historique
  public/assets/images/historyphoto.jpg
  src/Controller/PresentationController.php
  src/Model/HistoryManager.php
  src/View/Presentation/index.html.twig
Labels: Reviewed by PO

#43 Sprint04 us21 faq gestion
  src/Controller/FaqAdminController.php
  src/View/Faq/index.html.twig
  src/View/FaqAdmin/index.html.twig
Labels: Reviewed by PO

#38 add a container on admin layout
  src/View/layoutAdmin.html.twig
Labels: Corrections done, Reviewed by PO

#40 Sprint04 us63 qu est ce cest
  public/assets/images/whatIsIt.jpg
  src/Controller/PresentationController.php
  src/Model/WhatIsItManager.php
  src/View/Presentation/index.html.twig
Labels: Reviewed by PO

#44 Page Activités to dev
  public/assets/css/style.css
  public/assets/images/badminton.jpg
  public/assets/images/baseball.jpg
  public/assets/images/basket.jpg
  public/assets/images/football.jpg
  public/assets/images/gym.jpg
  public/assets/images/minigolf.jpeg
  public/assets/images/rugby.jpg
  public/assets/images/sumo.jpg
  src/Controller/ActivitiesController.php
  src/Model/ActivitiesManager.php
  src/View/Activities/index.html.twig
Labels: Reviewed by PO

#45 fix FAQ View
  src/View/Faq/index.html.twig
Labels: Reviewed by PO

#50 Navigation sur le site
  src/View/Stage/index.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#51 fix navbarUser
  src/View/_navbar.html.twig
Labels: Corrections done, Reviewed by PO

#52 contact form
  public/assets/css/contact.css
  public/index.php
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
Labels: Corrections done, Reviewed by PO

#53 final add for FAQ Admin
  public/assets/css/admin.css
  src/Controller/FaqAdminController.php
  src/Model/FaqManager.php
  src/View/FaqAdmin/_form.html.twig
  src/View/FaqAdmin/add.html.twig
  src/View/FaqAdmin/index.html.twig
  src/View/FaqAdmin/show.html.twig
  src/View/layoutAdmin.html.twig
Labels: Corrections done, Reviewed by PO

#58 Sprint4 us2 footer
  public/assets/css/style.css
  src/View/_footer.html.twig
Labels: Reviewed by PO

#59 fix mercredi hours
  src/View/Stage/index.html.twig
Labels: Reviewed by PO

#60 Fix navbarAdmin
  src/View/FaqAdmin/index.html.twig
  src/View/_navbarAdmin.htm.twig
  src/View/_navbarAdmin.html.twig
  src/View/layoutAdmin.html.twig
Labels: Corrections done, Reviewed by PO

#64 Réinsertion des liens de navigation US68
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#70 correction fix Add FAQ
  src/Controller/FaqAdminController.php
  src/View/FaqAdmin/index.html.twig
  src/View/FaqAdmin/show.html.twig
Labels: Reviewed by PO

#71 Fix Footer01
  public/assets/css/style.css
  src/View/_footer.html.twig
Labels: Reviewed by PO

#63 fix presentation cards
  public/assets/css/style.css
  src/View/Presentation/index.html.twig
Labels: Corrections done, Reviewed by PO

#72 Sprint4 isssue69 nostages
  public/assets/images/stages/zombie.jpg
  src/View/Stage/index.html.twig
Labels: Corrections done, Reviewed by PO

#76 Sprint4 issue75 session start
  public/index.php
Labels: Reviewed by PO

#74 fixed height carousel
  public/assets/css/style.css
  src/View/Home/_carousel.html.twig
Labels: Corrections done, Reviewed by PO

#77 ViewAdminInfrastructures
  src/Controller/PlacesAdminController.php
  src/View/PlacesAdmin/index.html.twig
Labels: Reviewed by PO

#56 final edit FAQ Admin
  public/assets/css/admin.css
  src/Controller/FaqAdminController.php
  src/Model/FaqManager.php
  src/View/FaqAdmin/_form.html.twig
  src/View/FaqAdmin/edit.html.twig
  src/View/FaqAdmin/index.html.twig
  src/View/layoutAdmin.html.twig
Labels: Changes requested

#55 final delete for FAQ admin
  src/Controller/FaqAdminController.php
  src/Model/FaqManager.php
  src/View/FaqAdmin/index.html.twig
  src/View/layoutAdmin.html.twig
Labels: Conflicts
